version: '2'
services:
  db:
    image: mysql:latest
    ports:
      - 3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=test
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=my_db
  test:
    build:
      context: ./
      dockerfile: Dockerfile
    links:
      - db
    command: bash -c '/usr/src/app/test-script.sh'
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=test
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=my_db
      - MYSQL_HOST=db