version: '2'
services:
  db:
    image: mysql:latest
    ports:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=${{MYSQL_PASSWORD}}
      - MYSQL_DATABASE=${{MYSQL_DATABASE}}
  test:
    build:
      context: ./
      dockerfile: Dockerfile
    links:
      - db
    command: bash -c 'sleep 30 && MYSQL_ROOT_PASSWORD=admin MYSQL_USER=my_user MYSQL_HOST=db MYSQL_PASSWORD=admin MYSQL_DATABASE=nodejs npm test'